In [2]:
a = [1,2,3]
b = [2,3,4]
res = []


In [7]:
for i in range(0,len(a)):
    res.append(a[i]*b[i])
res

[2, 6, 12, [2], [6], [12], 2, 6, 12]

In [8]:
import numpy as np

In [9]:
a = np.array([1,2,3])
b = np.array([2,3,4]),
c = a*b
c

array([[ 2,  6, 12]])

In [10]:
a = np.array([1,2,3,4,25])
type(a)

numpy.ndarray

In [11]:
b = np.array([1,3.14,52,8.5])
b

array([ 1.  ,  3.14, 52.  ,  8.5 ])

In [12]:
b = np.array([1,3.14,52,8.5], dtype = int)
b


array([ 1,  3, 52,  8])

In [13]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
np.ones((2,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [17]:
np.full((5,5),2,dtype=int)

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [18]:
np.ones(20)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [19]:
np.zeros((2,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [20]:
np.arange(0,20,5)

array([ 0,  5, 10, 15])

In [22]:
np.linspace(0,5,5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [24]:
np.random.normal(10,5,(2,2))
#np.random.normal(mean,sd,shape)

array([[ 6.26543643, 10.48462702],
       [ 9.23845814,  5.23070684]])

In [25]:
np.random.randint(0,10,(3,3))

array([[7, 2, 4],
       [0, 5, 3],
       [3, 4, 4]])

In [26]:
a = np.array([1,2,3,4,25])


In [27]:
a.ndim

1

In [28]:
a.dtype

dtype('int64')

In [29]:
a.size

5

In [30]:
len(a)

5

In [31]:
a.shape

(5,)

In [32]:
b = np.random.randint(20,size = (4,5))
b

array([[ 3, 12, 18,  5, 10],
       [17, 10, 18,  9,  2],
       [12, 15, 11, 19,  6],
       [ 3,  6,  5, 11, 14]])

In [33]:
b.ndim

2

In [34]:
b.size

20

In [35]:
b.dtype

dtype('int64')

In [36]:
a = np.random.normal(0,1,size=(3,5))
a

array([[ 0.34464141,  0.74101834, -0.41026461,  1.62332907,  0.71546622],
       [-2.53946787, -0.52117644,  0.9323775 ,  1.49166095, -0.01266243],
       [ 1.00042559, -0.80942374,  0.22079229,  0.37174332, -0.55313823]])

In [37]:
a.ndim

2

In [40]:
b = np.random.randint(0,10,10)
b

array([1, 1, 7, 0, 6, 2, 4, 7, 6, 2])

In [41]:
b.ndim

1

In [42]:
a = b.reshape(1,10)

a

array([[1, 1, 7, 0, 6, 2, 4, 7, 6, 2]])

In [43]:
a.ndim

2

In [47]:
a = np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
b = np.arange(10,20)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [49]:
c = np.concatenate([a,b]),
c

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19]),)

In [51]:
a = np.random.randint(0,20,size=(2,2))
a

array([[16, 15],
       [ 3, 10]])

In [52]:
b = np.random.randint(10,20,size=(2,2))
b

array([[17, 16],
       [11, 15]])

In [53]:
c = np.concatenate([a,b])
c

array([[16, 15],
       [ 3, 10],
       [17, 16],
       [11, 15]])

In [54]:
c = np.concatenate([a,b],axis=1)
c

array([[16, 15, 17, 16],
       [ 3, 10, 11, 15]])

In [55]:
#Splitting

In [56]:
a = np.array([0,1,25,25,1,0])


In [57]:
np.split(a,[2,4])

[array([0, 1]), array([25, 25]), array([1, 0])]

In [58]:
a,b,c = np.split(a,[2,4])
a

array([0, 1])

In [59]:
b

array([25, 25])

In [60]:
c

array([1, 0])

In [61]:
a = np.arange(0,20).reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [62]:
np.vsplit(a,[2])

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])]

In [63]:
a = np.arange(0,10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [67]:
np.hsplit(a,[3])


[array([[0, 1, 2],
        [5, 6, 7]]),
 array([[3, 4],
        [8, 9]])]

In [68]:
#sorting

In [69]:
a = np.array([2,4,5,13,3,1,28,5])
a

array([ 2,  4,  5, 13,  3,  1, 28,  5])

In [70]:
np.sort(a)

array([ 1,  2,  3,  4,  5,  5, 13, 28])

In [71]:
a

array([ 2,  4,  5, 13,  3,  1, 28,  5])

In [72]:
a.sort()


In [73]:
a

array([ 1,  2,  3,  4,  5,  5, 13, 28])

In [74]:
a = np.random.randint(0,10,size=(2,5))
a

array([[4, 3, 5, 5, 4],
       [9, 7, 0, 1, 1]])

In [75]:
np.sort(a,axis=1)

array([[3, 4, 4, 5, 5],
       [0, 1, 1, 7, 9]])

In [76]:
np.sort(a,axis=0)

array([[4, 3, 0, 1, 1],
       [9, 7, 5, 5, 4]])